config/routes.rb
RavelryVisualizer::Application.routes.draw do

  resources :accounts
  resources :visualize, :only => [:index, :show]

  if Rails.env.development?
    resources :pages 
  else
    resources :pages, :only => [:show]
  end

  root :to => "Visualize#show", :id => "joeshmo"

end

app/views/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :visibility
    = f.text_field :visibility
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Slug
    %th Title
    %th Visibility
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.slug
      %td= page.title
      %td= page.visibility
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
- content_for :title do
  = @page.title

%header
  %h1= @page.title
%article{:id => @page.slug}
  = @page.body.html_safe