config/routes.rb
RavelryVisualizer::Application.routes.draw do

  resources :accounts
  resources :visualize, :only => [:index, :show]

  if Rails.env.development?
    resources :pages 
  else
    resources :pages, :only => [:show]
  end

  root :to => "Visualize#show", :id => "joeshmo"

end

app/models/account.rb
class Account < ActiveRecord::Base
  @@url_base_format = "http://api.ravelry.com/projects/%s/progress.json"
  @@cache_expiration = 1.day
  @@cache_dir = "tmp/ravelry"
  
  attr_accessible :api_key, :username
  attr_accessor :data
  after_initialize :pull
  validate :ravelry_authenticates, :on => :create


  def pull
    unless username.nil?
      load_cache
      if @data.nil?
        begin
          raw_data = RestClient.get @@url_base_format % username, {:params => {:key => api_key, :status => "finished" }}
        
          @data = JSON.parse(raw_data)
p @data
        rescue
        end
          
        save_cache
      end
      @data
    end
  end

  def pronouns
    if username == "joeshmo"
      {:i => "I", :me => "me", :mine => "mine", :my => "my", :myself => "myself"}
    else
      {:i => "you", :me => "you", :mine => "your", :my => "your",  :myself => "yourself"}
    end
  end

  def visitor?
    username != "joeshmo"
  end

  def invalid_api_key
    errors[:base] << "API key incorrect"
  end
  protected

  #disabled caching.  Heroku does not seem to want me writing files in /tmp

  def load_cache
    return false

    if File.exists?(cache_filename)
      File.open(cache_filename, "r") do |f|
        save_date = f.readline.to_datetime
        if ( save_date + @@cache_expiration > DateTime.now )
          @data = JSON.parse(f.readline)
        end
      end
    end
  end

  def save_cache
    return false

    unless @data.nil?
      File.open(cache_filename, "w") do |f|
        f.puts(DateTime.now)
        f.puts(JSON.generate(@data))
      end
    end
  end

  def cache_filename
    "#{@@cache_dir}/#{api_key}"
  end

  def ravelry_authenticates
    pull
    errors[:base] << "Username and API key don't match." if @data.nil?
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @accounts }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to visualize_path(@account.username), :notice => 'Account was successfully created.' }
        format.json { render :json => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])
    
    # :( broke rest here, used the update for delete, because I am requiring input for delete

    if params[:delete][:confirm]  and params[:account][:api_key] == @account.api_key
      destroy
    else
      respond_to do |format|
        @account.invalid_api_key
        format.html { render :action => "edit" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def statistics(data)
    me_words = ["me", "myself", "mine"]
    s = { :favorite => nil, :conversational => nil }
    
    if data["projects"].length
      s[:favorite] = data["projects"].max{|a,b| a["favorited"] <=> b["favorited"] }
      s[:conversational] = data["projects"].max{|a,b| a["comments"] <=> b["comments"] }

      s[:happiness] = Array.new(5) { Array.new }
      s[:gifts] = {:self => 0, :others => 0, :blank => 0, :names => Hash.new(0)}
      data["projects"].each do |project| 
        s[:happiness][project["happiness"].to_i] << project["name"] 
        
        if project["madeFor"]
          if me_words.any?{|word| project["madeFor"].downcase.include? word }
            s[:gifts][:self] += 1
          else
            s[:gifts][:others] += 1
            s[:gifts][:names][project["madeFor"]] += 1
          end
        else
          s[:gifts][:blank] += 1
        end
      end

    end

    s[:names] = ["loser", "unhappy", "meh", "smile", "grin"]
    s[:emoticon_format] = "http://ravelry.com/images/emoticon_%s.png"
    s
  end

  def speed(data)
    s = { :duration => nil, :rate => { :year => nil, :month => nil, :week => nil } }

    if data["projects"].length
      seasons = { :started => Hash.new(0), :completed => Hash.new(0) }
      durations = []
      short = 0
      long = 0
      earliest = Date.today

      data["projects"].select{|p| p["status"] == "finished" and p["completed"] and p["started"]}.each do |project|
        completed = project["completed"].to_date
        started = project["started"].to_date
        
        duration = (completed - started)
        durations << duration.days

        seasons[:started][started.season] += 1
        seasons[:completed][completed.season] += 1

        earliest = started if started < earliest
        


        if ( duration.days < 3.months )
          short += 1
        else
          long += 1
        end
      end

      s[:yearly] = data["projects"].select{|p| p["completed"]}.group_by{|p| p["completed"].to_date.year}

      s[:duration] = durations.mean
      s[:durations] = durations
      s[:seasons] = {}
      seasons.each do |name, counts|
        most = counts.sort{|a,b| b[1]<=>a[1]}.collect{|pair| pair[0].to_s.capitalize}.first(2)
        s[:seasons][name] = most
      end
      s[:seasons][:same] = false
      s[:seasons][:same] = true if s[:seasons][:started].all?{|season| s[:seasons][:completed].include? season}
      s[:short] = short
      s[:long] = long
    end

    s
  end

  def tools(data)
    t = {}
   
    #where my hooks at?

    needles_raw = data["projects"].collect{|p| p["needles"]}
    blank_ratio = needles_raw.select(&:empty?).count / needles_raw.count.to_f
    needles = needles_raw.reject(&:empty?).flatten.uniq.index_by{|needle| needle["metric"]}
    grouped = needles_raw.reject(&:empty?).flatten.group_by{|needle| needle["metric"]}

    favorites = needles.keys.collect{|metric| [metric, grouped[metric].length]}.sort{|a,b| b[1] <=> a[1]}.first(5)
    
    t[:needles] = needles
    t[:blank_ratio] = blank_ratio
    t[:favorites] = favorites
    t
  end
  
  def yarn(data)
    y = {}

    project_yarns = data["projects"].collect{|p| p["yarns"]}
    y[:blank_ratio] = project_yarns.select(&:empty?).count / project_yarns.count.to_f
    y[:yarns] = project_yarns.reject(&:empty?).flatten.uniq.index_by{|yarn| yarn["name"]}
    y[:brands] = project_yarns.reject(&:empty?).flatten.uniq.index_by{|yarn| yarn["brand"]}

    brand_popularity = y[:brands].collect do |(brand,yarn)|
      [brand, data["projects"].select{|p| p["yarns"].include? yarn}.length]
    end
    y[:favorite_brands] = brand_popularity.sort{|a,b| b[1] <=> a[1]}.first(3)

    yarn_popularity = y[:yarns].collect do |(name, yarn)|
      [name, data["projects"].select{|p| p["yarns"].include? yarn}.length]
    end
p yarn_popularity
    y[:favorite_yarn] = yarn_popularity.sort{|a,b| b[1] <=> a[1]}.first

    y
  end
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :api_key 
    = f.text_field :api_key, :size => 40
    %div
      %small
        %em
          This is 
          %strong not 
          your password, you can get yours
          = link_to "here", "http://www.ravelry.com/help/api"
  .actions
    = f.submit 'Save'

  %br

app/views/accounts/edit.html.haml
%h1 Editing account

- @account.api_key = ""
= form_for @account do |f|
  -if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
  = hidden_field :delete, :confirm, :value => 1
  .field
    = f.label :api_key 
    = f.text_field :api_key, :size => 40
    %div
      %small
        %em
          Please provide again to confirm, it is available 
          = link_to "here", "http://www.ravelry.com/help/api"
  .actions
    = f.submit 'Delete'

app/views/accounts/index.html.haml
%header
  %h1 Accounts

%table
  %tr
    %th Username
    %th
    %th
    %th

  - @accounts.each do |account|
    %tr
      %td= account.username
      %td= link_to 'Show', visualize_path(account.username)
      %td= link_to 'Delete', edit_account_path(account)
      -#%td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%header
  %h1 Try it
%p
  Just enter your Ravelry username and api key and you can see your data.

= render 'form'


- content_for :title do 
  Signup

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @account.username
%p
  %b Api key:
  = @account.api_key

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path